### ISSUE TITLE
Error installation 

### ISSUE THREAD

**Issue by demon1977** [wouterdebie/uhppote-mqtt#1]
Can't install ghcr.io/wouterdebie/armv7-uhppote-mqtt:0.0.14: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=0.0.14&fromImage=ghcr.io%2Fwouterdebie%2Farmv7-uhppote-mqtt&platform=linux%2Farm%2Fv7: Internal Server Error ("Head https://ghcr.io/v2/wouterdebie/armv7-uhppote-mqtt/manifests/0.0.14: denied")

**Comment by wouterdebie** [comment]
Hi!

Thanks for this. I didn't realize the armv7 build failed. I've fixed it and the image should be available. Can you check?
